'use client';
import {useEffect,useMemo,useState} from 'react';
const courses=[
['foundations','MODULE 01','2 weeks','Beginner','How AI Actually Works','Tokens, neural networks, and next-token prediction — the real mechanics, no hype.'],
['foundations','MODULE 02','2 weeks','Beginner','Prompt Engineering Fundamentals','Write prompts that actually control model behavior — structure, constraints, and failure modes.'],
['foundations','MODULE 03','2 weeks','Beginner','AI for Business Leaders','Where AI actually saves time or money in a business — and where it does not yet.'],
['foundations','MODULE 04','1 week','Beginner','Math for Machine Learning','Just enough linear algebra, probability, and calculus to understand how models learn.'],
['engineering','MODULE 05','3 weeks','Intermediate','Building with LLM APIs','Ship a working AI feature: API integration, streaming responses, and basic tool use.'],
['engineering','MODULE 06','4 weeks','Advanced','Fine-tuning & RAG in Practice','Adapt a model to your own data — from embeddings to a working retrieval pipeline.'],
['engineering','MODULE 07','3 weeks','Advanced','AI Agents & Tool Use','Design multi-step agents that call tools, use memory, and recover from failure.'],
['engineering','MODULE 08','3 weeks','Intermediate','AI Product Design & UX','Design conversational and agentic interfaces people actually trust and want to use.'],
['engineering','MODULE 09','2 weeks','Advanced','Evaluating & Shipping AI Safely','Testing, red-teaming, and monitoring AI features before and after launch.'],
['trendify','MODULE 10','1 week','Intermediate','Understanding Tiff AI','How Tiff AI is built — architecture, connectors, and the design decisions behind the product.'],
['trendify','MODULE 11','2 weeks','Intermediate','Inside TAM: Trendify Advanced Models','How TAM is trained and fine-tuned, and what makes an advanced model different from a base model.'],
['trendify','MODULE 12','2 weeks','Intermediate','TAM Cultural: Culturally-Aware AI','Building language models that respect local context — lessons from culturally aware AI research.']
];
const trackNames={foundations:'Track 01 · AI Foundations',engineering:'Track 02 · AI Engineering',trendify:'Track 03 · Trendify Models'};
const lessons=['Introduction','Core concepts','Hands-on lab','Applied exercise','Final project'];
export default function Home(){const [tab,setTab]=useState('all'),[search,setSearch]=useState(''),[user,setUser]=useState(null),[enrolled,setEnrolled]=useState([]),[modal,setModal]=useState(null),[email,setEmail]=useState(''),[cert,setCert]=useState(''),[certMsg,setCertMsg]=useState('');
useEffect(()=>{try{setUser(JSON.parse(localStorage.getItem('ta_user')));setEnrolled(JSON.parse(localStorage.getItem('ta_enrolled')||'[]'))}catch{}},[]);
const filtered=useMemo(()=>courses.filter(c=>(tab==='all'||c[0]===tab)&&`${c[4]} ${c[5]}`.toLowerCase().includes(search.toLowerCase())),[tab,search]);
function createAccount(e){e.preventDefault();if(!email)return;const u={email};localStorage.setItem('ta_user',JSON.stringify(u));setUser(u);setEmail('');document.getElementById('dashboard').scrollIntoView({behavior:'smooth'})}
function enroll(c){if(!user){document.getElementById('signup').scrollIntoView({behavior:'smooth'});return}const next=[...new Set([...enrolled,c[4]])];setEnrolled(next);localStorage.setItem('ta_enrolled',JSON.stringify(next));}
return <><div className="glow"/><header><a className="logo" href="#top">trendify<span>academy</span></a><nav><a href="#courses">Courses</a><a href="#how">How it works</a><a href="#dashboard">Dashboard</a><a href="#verify">Verify</a></nav><button className="btn ghost" onClick={()=>document.getElementById(user?'dashboard':'signup').scrollIntoView({behavior:'smooth'})}>{user?'Dashboard':'Sign in'}</button></header><main id="top">
<section className="hero"><div className="heroGrid"><div><div className="eyebrow">Free AI School · Nairobi</div><h1>A full AI education.<br/>Always <span className="grad">free</span>.</h1><p>Trendify Academy takes learners from first principles to AI engineering and Trendify model architecture. Learn by building, complete projects, and earn a verifiable Trendify credential.</p><div className="actions"><button className="btn" onClick={()=>document.getElementById('courses').scrollIntoView({behavior:'smooth'})}>Browse courses</button><button className="btn ghost" onClick={()=>document.getElementById('how').scrollIntoView({behavior:'smooth'})}>How it works</button></div><div className="stats"><div><b>Free</b><small>every course</small></div><div><b>3</b><small>learning tracks</small></div><div><b>12</b><small>core courses</small></div><div><b>100%</b><small>project based</small></div></div></div><div className="credential"><div className="credTop"><div className="mark">T</div><div className="credId">CERT ID<br/>TA-2026-0417</div></div><div className="credTitle">Prompt Engineering Fundamentals</div><div className="muted">Awarded to Amara Otieno</div><div className="verified">● Verified · Trendify Academy</div></div></div></div></section>
<section id="how"><div className="eyebrow">How it works</div><h2>Three steps from enrollment to credential</h2><div className="steps">{[['01','Enroll in a course','Pick a short course and learn at your own pace.'],['02','Build through modules','Work through lessons, labs, and a final project.'],['03','Earn your certificate','Complete the project and unlock a verifiable credential.']].map(x=><div className="step" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
<section id="courses"><div className="sectionHead"><div><div className="eyebrow">Course catalog</div><h2>A complete AI school, at no cost</h2></div><input className="search" placeholder="Search courses…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="tabs">{[['all','All courses'],['foundations','AI Foundations'],['engineering','AI Engineering'],['trendify','Trendify Models']].map(t=><button key={t[0]} className={'tab '+(tab===t[0]?'active':'')} onClick={()=>setTab(t[0])}>{t[1]}</button>)}</div>{Object.keys(trackNames).map(track=>{const list=filtered.filter(c=>c[0]===track);if(!list.length)return null;return <div className="track" key={track}><div className="trackLabel">{trackNames[track]}</div><div className="grid">{list.map(c=><article className="card" key={c[4]} onClick={()=>setModal(c)}><div className="cardTop"><span className="tag">{c[1]}</span><span className="duration">{c[2]}</span></div><h3>{c[4]}</h3><p>{c[5]}</p><div className="cardMeta"><span>{c[3]}</span><span className="arrow">→</span></div></article>)}</div></div>})}</section>
<section id="dashboard"><div className="panel"><div className="eyebrow">Student dashboard</div>{user?<><div className="dashHead"><div><h2>Welcome back.</h2><p className="muted">{user.email}</p></div><button className="btn ghost" onClick={()=>{localStorage.removeItem('ta_user');localStorage.removeItem('ta_enrolled');setUser(null);setEnrolled([])}}>Sign out</button></div><div className="progress"><span style={{width:`${Math.min(100,Math.round(enrolled.length/12*100))}%`}}/></div><p className="muted">{enrolled.length} course{enrolled.length===1?'':'s'} enrolled · {Math.round(enrolled.length/12*100)}% catalog progress</p><div className="rows">{enrolled.length?enrolled.map(n=><div className="row" key={n}><b>{n}</b><span className="verified">ENROLLED</span></div>):<p className="muted">No courses yet. Browse the catalog above.</p>}</div></>:<div><h2>Your learning space.</h2><p className="muted">Create a free account to track enrollments and course progress.</p></div>}</div></section>
<section id="verify"><div className="panel verify"><div><div className="eyebrow">Credential verification</div><h2>Verify a Trendify certificate.</h2><p className="muted">Enter a credential ID to validate a certificate issued by Trendify Academy.</p><input className="search full" value={cert} onChange={e=>setCert(e.target.value)} placeholder="TA-2026-0417"/><button className="btn" onClick={()=>setCertMsg(cert.toUpperCase()==='TA-2026-0417'?'✓ Valid credential — Prompt Engineering Fundamentals, awarded to Amara Otieno.':'Credential not found. Check the ID and try again.')}>Verify credential</button><p className="verifyMsg">{certMsg}</p></div><div className="certificate"><div className="mark">T</div><div className="muted">TRENDIFY ACADEMY</div><div className="big">Prompt Engineering Fundamentals</div><div className="muted">Amara Otieno</div><div className="verified">TA-2026-0417 · VALID</div></div></div></section>
<section id="signup"><div className="cta"><div className="eyebrow center">Get started · No cost, ever</div><h2>Start your first course</h2><p className="muted">Create a free student account and start learning immediately.</p><form onSubmit={createAccount} className="signup"><input type="email" required placeholder="you@email.com" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn">Create account</button></form></div></section>
</main><footer><span>© 2026 Trendify Academy · Free AI education, Nairobi, Kenya</span><span>academy.trendify.co.ke</span></footer>{modal&&<div className="modal" onClick={e=>e.target===e.currentTarget&&setModal(null)}><div className="modalBox"><button className="close" onClick={()=>setModal(null)}>×</button><div className="eyebrow">{modal[1]} · {trackNames[modal[0]].replace(/^Track \d+ · /,'')}</div><h2>{modal[4]}</h2><p className="muted">{modal[5]}</p><div className="lessons">{lessons.map((l,i)=><div className="lesson" key={l}><span>{String(i+1).padStart(2,'0')} · {l}</span><span>{i===4?'Final project':'Lesson'}</span></div>)}</div><button className="btn" onClick={()=>enroll(modal)}>{enrolled.includes(modal[4])?'Enrolled':'Enroll in course'}</button></div></div>}</>}
